# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/flashtrain',
                'doc_host': 'https://NLTuan.github.io',
                'git_url': 'https://github.com/NLTuan/flashtrain',
                'lib_path': 'flashtrain'},
  'syms': {'flashtrain.core': {'flashtrain.core.foo': ('core.html#foo', 'flashtrain/core.py')}}}
